#!/usr/bin/env python3


import numpy as np


def combineFiles(effFiles,outputFile):

    newData = None
    nf = 0
    for effFile in effFiles:
        effData = np.genfromtxt(effFile,names=True,
                                case_sensitive='lower',
                                skip_header=2,delimiter=',')        
        nf += 1
        if newData is None:
            newData = np.array(effData,dtype=effData.dtype)
        else:
            newData = np.append(newData,effData,axis=0)
        # print(nf,len(newData))
    

    np.savetxt(outputFile,newData,delimiter=',',header=','.join(newData.dtype.names),fmt='%1.3e')


if __name__ == "__main__":
    
    import argparse    
    ap = argparse.ArgumentParser(description=
            "Merge individual csv datas generated by getEffsFromROOT.py.")
    ap.add_argument('-f', '--inputFiles', required=True,nargs='+',
            help='list of csv files to be merged', default =[])
    
    ap.add_argument('-o', '--outputFile', required=False, help='output file.',
                    default='b2tf_trigger_effs.csv')


    args = ap.parse_args()
    inputFiles = args.inputFiles
    outputFile = args.outputFile
    
    combineFiles(inputFiles,outputFile)







