(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"DipoleDM",
  Authors -> {"Andre Lessa"},
  Emails -> {"andre.lessa@ufabc.edu.br"},
  Date -> "03.12.2024",
  Version -> "1",
  URLs -> ""};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], chi0 -> F[13], chi1 -> F[14], chi2 -> F[15], Sd -> S[4]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

IndexRange[ Index[DarkGen] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

F[13] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> M0,
    Indices -> {},
    PropagatorLabel -> "chi0" },

F[14] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> M1,
    Indices -> {},
    PropagatorLabel -> "chi1" },

F[15] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> M2,
    Indices -> {},
    PropagatorLabel -> "chi2" },

S[4] == {
    SelfConjugate -> True,
    QuantumNumbers -> {},
    PropagatorType -> Scalar,
    PropagatorArrow -> None,
    Mass -> MSd,
    Indices -> {},
    PropagatorLabel -> "Sd" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MTA[ ___ ] := MTA;
MT[ ___ ] := MT;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
M0[ ___ ] := M0;
M1[ ___ ] := M1;
M2[ ___ ] := M2;
MSd[ ___ ] := MSd;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam1, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam1, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam1, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*(lam3*sina^2 - 2*lam1*(-1 + sina^2)), 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-I)*(lam3*sina^2 - 2*lam1*(-1 + sina^2)), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*(lam1*(-1 + sina^2)^2 + sina^2*(lam3 + lam2*sina^2 - lam3*sina^2)), 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(lam3 + 2*lam1*sina^2 - lam3*sina^2), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*(lam3 + 2*lam1*sina^2 - lam3*sina^2), 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(-6*(lam1 + lam2)*sina^2*(-1 + sina^2) + lam3*(1 - 6*sina^2 + 6*sina^4)), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*(lam2*(-1 + sina^2)^2 + sina^2*(lam3 + lam1*sina^2 - lam3*sina^2)), 0}},

C[ S[2] , S[2] , S[1] , S[4] ] == {{(-I)*(2*lam1 - lam3)*sina*Sqrt[1 - sina^2], 0}},

C[ S[3] , -S[3] , S[1] , S[4] ] == {{(-I)*(2*lam1 - lam3)*sina*Sqrt[1 - sina^2], 0}},

C[ S[1] , S[1] , S[1] , S[4] ] == {{(3*I)*sina*Sqrt[1 - sina^2]*(lam3 + 2*lam2*sina^2 - 2*lam3*sina^2 + 2*lam1*(-1 + sina^2)), 0}},

C[ S[1] , S[4] , S[4] , S[4] ] == {{(-3*I)*sina*Sqrt[1 - sina^2]*(lam3 + 2*lam1*sina^2 - 2*lam3*sina^2 + 2*lam2*(-1 + sina^2)), 0}},

C[ S[2] , S[2] , S[4] ] == {{(-I)*(2*lam1*sina*vev + lam3*Sqrt[1 - sina^2]*vevD), 0}},

C[ S[3] , -S[3] , S[4] ] == {{(-I)*(2*lam1*sina*vev + lam3*Sqrt[1 - sina^2]*vevD), 0}},

C[ S[1] , S[1] , S[4] ] == {{I*(6*lam1*sina*(-1 + sina^2)*vev - 6*lam2*sina^2*Sqrt[1 - sina^2]*vevD + lam3*(2*sina*vev - 3*sina^3*vev - Sqrt[1 - sina^2]*vevD + 3*sina^2*Sqrt[1 - sina^2]*vevD)), 0}},

C[ S[4] , S[4] , S[4] ] == {{(3*I)*(lam3*sina*((-1 + sina^2)*vev - sina*Sqrt[1 - sina^2]*vevD) - 2*(lam1*sina^3*vev + lam2*(1 - sina^2)^(3/2)*vevD)), 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam1*Sqrt[1 - sina^2]*vev + I*lam3*sina*vevD, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam1*Sqrt[1 - sina^2]*vev + I*lam3*sina*vevD, 0}},

C[ S[1] , S[1] , S[1] ] == {{(3*I)*(-2*lam1*(1 - sina^2)^(3/2)*vev + 2*lam2*sina^3*vevD + lam3*sina*(-(sina*Sqrt[1 - sina^2]*vev) + vevD - sina^2*vevD)), 0}},

C[ S[1] , S[4] , S[4] ] == {{I*(-6*sina*(lam1*sina*Sqrt[1 - sina^2]*vev + lam2*(-1 + sina^2)*vevD) + lam3*(Sqrt[1 - sina^2]*(-1 + 3*sina^2)*vev + sina*(-2 + 3*sina^2)*vevD)), 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc24, 0}, {I*gc24, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc25*IndexDelta[e1x2, e2x2], 0}, {I*gc25*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ S[4] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc26*IndexDelta[e1x2, e2x2], 0}, {I*gc26*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc27, 0}, {I*gc27, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc28, 0}, {I*gc28, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc30, 0}, {I*gc30, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(EL^2*vev)/sw^2, 0}},

C[ S[4] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*sina*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*Sqrt[1 - sina^2]*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc35, 0}, {I*gc35, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc37, 0}, {I*gc37, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc39, 0}, {I*gc39, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[4] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*sina*vev)/sw^2, 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*Sqrt[1 - sina^2]*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc43, 0}, {I*gc43, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc44, 0}, {I*gc44, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(EL^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc46, 0}, {I*gc46, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc48, 0}, {I*gc48, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(EL^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc50, 0}, {I*gc50, 0}, {0, 0}},

C[ S[4] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*sina*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*Sqrt[1 - sina^2]*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[13] , F[14] , S[2] , S[2] ] == {{I*gc53, 0}, {I*gc53, 0}},

C[ -F[13] , F[14] , S[3] , -S[3] ] == {{I*gc54, 0}, {I*gc54, 0}},

C[ -F[13] , F[14] , S[1] , S[1] ] == {{I*gc55, 0}, {I*gc55, 0}},

C[ -F[13] , F[14] , S[4] , S[4] ] == {{I*gc56, 0}, {I*gc56, 0}},

C[ -F[13] , F[14] , S[1] , S[4] ] == {{I*gc57, 0}, {I*gc57, 0}},

C[ -F[13] , F[14] , S[4] ] == {{I*gc58, 0}, {I*gc58, 0}},

C[ -F[13] , F[14] , S[1] ] == {{I*gc59, 0}, {I*gc59, 0}},

C[ -F[14] , F[13] , S[2] , S[2] ] == {{I*gc60, 0}, {I*gc60, 0}},

C[ -F[14] , F[13] , S[3] , -S[3] ] == {{I*gc61, 0}, {I*gc61, 0}},

C[ -F[14] , F[13] , S[1] , S[1] ] == {{I*gc62, 0}, {I*gc62, 0}},

C[ -F[14] , F[13] , S[4] , S[4] ] == {{I*gc63, 0}, {I*gc63, 0}},

C[ -F[14] , F[13] , S[1] , S[4] ] == {{I*gc64, 0}, {I*gc64, 0}},

C[ -F[14] , F[13] , S[4] ] == {{I*gc65, 0}, {I*gc65, 0}},

C[ -F[14] , F[13] , S[1] ] == {{I*gc66, 0}, {I*gc66, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc67*FASUNF[e3x2, e1x1, e2x1], 0}, {gc67*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc68*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc68*FASUNF[e1x2, e2x2, e3x2], 0}, {gc68*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc68*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc68*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc68*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc69*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc69*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc69*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc70*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc70*FASUNF[e1x2, e2x2, e3x2], 0}, {gc70*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc70*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc70*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc70*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc71*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc71*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc71*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[4] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc72*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc72*FASUNF[e1x2, e2x2, e3x2], 0}, {gc72*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc72*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc72*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc72*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ S[4] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc73*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc73*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc73*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc74L*IndexDelta[e1x2, e2x2], 0}, {gc74R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc75L*IndexDelta[e1x2, e2x2], 0}, {gc75R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] ] == {{I*gc76*IndexDelta[e1x2, e2x2], 0}, {I*gc76*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc77*IndexDelta[e1x2, e2x2], 0}, {I*gc77*IndexDelta[e1x2, e2x2], 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc78, 0}, {0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc79L, 0}, {gc79R, 0}},

C[ -F[6] , F[6] , S[4] ] == {{I*gc80, 0}, {I*gc80, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc81, 0}, {I*gc81, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc82L*IndexDelta[e1x2, e2x2], 0}, {gc82R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc83L*IndexDelta[e1x2, e2x2], 0}, {gc83R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{I*gc84*IndexDelta[e1x2, e2x2], 0}, {I*gc84*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc85*IndexDelta[e1x2, e2x2], 0}, {I*gc85*IndexDelta[e1x2, e2x2], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ -S[3] , S[4] , V[1] , V[3] ] == {{-1/2*(EL^2*sina)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*(EL^2*Sqrt[1 - sina^2])/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {gc89, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc90, 0}, {I*gc90, 0}},

C[ -S[3] , S[4] , V[3] ] == {{-gc91, 0}, {gc91, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc92, 0}, {gc92, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc93, 0}, {I*gc93, 0}, {I*gc93, 0}, {(-I)*gc93, 0}, {(-I)*gc93, 0}, {I*gc93, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(EL^2*sina)/(2*sw), 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{(EL^2*Sqrt[1 - sina^2])/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{0, 0}, {0, 0}, {gc97, 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc98, 0}, {I*gc98, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc99, 0}, {gc99, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc100, 0}, {gc100, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((-1/2*I)*EL^2*(-1 + sina)*(1 + sina))/sw^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*sina^2)/sw^2, 0}},

C[ S[1] , S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*sina*Sqrt[1 - sina^2])/sw^2, 0}},

C[ S[4] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc106, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc107, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc108, 0}, {(-I)*gc108, 0}, {(2*I)*gc108, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc109, 0}, {I*gc109, 0}, {I*gc109, 0}, {(-I)*gc109, 0}, {(-I)*gc109, 0}, {I*gc109, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc110, 0}, {(-I)*gc110, 0}, {(2*I)*gc110, 0}},

C[ -F[13] , F[15] , S[1] ] == {{I*gc111, 0}, {I*gc111, 0}},

C[ -F[13] , F[15] , S[4] ] == {{I*gc112, 0}, {I*gc112, 0}},

C[ -F[15] , F[13] , S[1] ] == {{I*gc113, 0}, {I*gc113, 0}},

C[ -F[15] , F[13] , S[4] ] == {{I*gc114, 0}, {I*gc114, 0}},

C[ -F[14] , F[15] , S[1] ] == {{I*gc115, 0}, {I*gc115, 0}},

C[ -F[14] , F[15] , S[4] ] == {{I*gc116, 0}, {I*gc116, 0}},

C[ -F[15] , F[14] , S[1] ] == {{I*gc117, 0}, {I*gc117, 0}},

C[ -F[15] , F[14] , S[4] ] == {{I*gc118, 0}, {I*gc118, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc119R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[4] , V[2] ] == {{-gc121, 0}, {gc121, 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc122, 0}, {gc122, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc123, 0}, {I*gc123, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[4] , V[3] , V[2] ] == {{(EL^2*sina)/(2*cw), 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{(EL^2*Sqrt[1 - sina^2])/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {gc127, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-1/2*(EL^2*sina)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*(EL^2*Sqrt[1 - sina^2])/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {gc131, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc132, 0}, {I*gc132, 0}, {I*gc132, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((-1/2*I)*EL^2*(-1 + sina)*(1 + sina)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*sina^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*sina*Sqrt[1 - sina^2]*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc138, 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc139, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc140, 0}, {(-I)*gc140, 0}, {(2*I)*gc140, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc141, 0}, {I*gc141, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc142, 0}, {I*gc142, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc143, 0}, {I*gc143, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc144*IndexDelta[e1x2, e2x2], 0}, {I*gc144*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc145*IndexDelta[e1x2, e2x2], 0}, {I*gc145*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc146*IndexDelta[e1x2, e2x2], 0}, {I*gc146*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc147*IndexDelta[e1x2, e2x2], 0}, {I*gc147*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc148*IndexDelta[e1x2, e2x2], 0}, {I*gc148*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc149*IndexDelta[e1x2, e2x2], 0}, {I*gc149*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc150*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc150*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc151*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc151*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc152*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc152*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc153*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc153*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc154*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc154*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc155*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc155*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc156*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc157*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc158*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc159*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc160*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc161*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc162, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc163, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc164, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc165, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc166, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc167, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc168L*IndexDelta[e1x2, e2x2], 0}, {I*gc168R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc169L*IndexDelta[e1x2, e2x2], 0}, {I*gc169R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc170L*IndexDelta[e1x2, e2x2], 0}, {I*gc170R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc171L*IndexDelta[e1x2, e2x2], 0}, {I*gc171R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc172L*IndexDelta[e1x2, e2x2], 0}, {I*gc172R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc173L*IndexDelta[e1x2, e2x2], 0}, {I*gc173R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc174, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc175, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc176, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc177L, 0}, {I*gc177R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc178L, 0}, {I*gc178R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc179L, 0}, {I*gc179R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc24 -> -EL,
     gc25 -> GGH,
     gc26 -> GGS,
     gc27 -> EL,
     gc28 -> -EL,
     gc30 -> EL,
     gc34 -> -EL,
     gc35 -> -((cw*EL)/sw),
     gc37 -> (cw*EL)/sw,
     gc39 -> -EL,
     gc43 -> EL,
     gc44 -> (cw*EL)/sw,
     gc46 -> -((cw*EL)/sw),
     gc48 -> (cw*EL)/sw,
     gc50 -> -((cw*EL)/sw),
     gc53 -> -(Chxx1x2/LambdaUV),
     gc54 -> -(Chxx1x2/LambdaUV),
     gc55 -> (Chxx1x2*(-1 + sina^2))/LambdaUV,
     gc56 -> -((Chxx1x2*sina^2)/LambdaUV),
     gc57 -> -((Chxx1x2*sina*Sqrt[1 - sina^2])/LambdaUV),
     gc58 -> -((Chxx1x2*sina*vev)/LambdaUV),
     gc59 -> -((Chxx1x2*Sqrt[1 - sina^2]*vev)/LambdaUV),
     gc60 -> -(Chxx1x2/LambdaUV),
     gc61 -> -(Chxx1x2/LambdaUV),
     gc62 -> (Chxx1x2*(-1 + sina^2))/LambdaUV,
     gc63 -> -((Chxx1x2*sina^2)/LambdaUV),
     gc64 -> -((Chxx1x2*sina*Sqrt[1 - sina^2])/LambdaUV),
     gc65 -> -((Chxx1x2*sina*vev)/LambdaUV),
     gc66 -> -((Chxx1x2*Sqrt[1 - sina^2]*vev)/LambdaUV),
     gc67 -> GS,
     gc68 -> -GS,
     gc69 -> -GS^2,
     gc70 -> -(GGH*GS),
     gc71 -> -(GGH*GS^2),
     gc72 -> -(GGS*GS),
     gc73 -> -(GGS*GS^2),
     gc74L -> yb,
     gc74R -> -yt,
     gc75L -> -(yb/Sqrt[2]),
     gc75R -> yb/Sqrt[2],
     gc76 -> -((sina*yb)/Sqrt[2]),
     gc77 -> -((Sqrt[1 - sina^2]*yb)/Sqrt[2]),
     gc78 -> ytau,
     gc79L -> -(ytau/Sqrt[2]),
     gc79R -> ytau/Sqrt[2],
     gc80 -> -((sina*ytau)/Sqrt[2]),
     gc81 -> -((Sqrt[1 - sina^2]*ytau)/Sqrt[2]),
     gc82L -> yt,
     gc82R -> -yb,
     gc83L -> yt/Sqrt[2],
     gc83R -> -(yt/Sqrt[2]),
     gc84 -> -((sina*yt)/Sqrt[2]),
     gc85 -> -((Sqrt[1 - sina^2]*yt)/Sqrt[2]),
     gc89 -> -1/2*(EL^2*vev)/sw,
     gc90 -> EL/(2*sw),
     gc91 -> -1/2*(EL*sina)/sw,
     gc92 -> -1/2*(EL*Sqrt[1 - sina^2])/sw,
     gc93 -> EL,
     gc97 -> (EL^2*vev)/(2*sw),
     gc98 -> -1/2*EL/sw,
     gc99 -> -1/2*(EL*sina)/sw,
     gc100 -> -1/2*(EL*Sqrt[1 - sina^2])/sw,
     gc106 -> (EL^2*sina*vev)/(2*sw^2),
     gc107 -> (EL^2*Sqrt[1 - sina^2]*vev)/(2*sw^2),
     gc108 -> -EL^2,
     gc109 -> (cw*EL)/sw,
     gc110 -> EL^2/sw^2,
     gc111 -> (sina*ychi1x3)/Sqrt[2],
     gc112 -> -((Sqrt[1 - sina^2]*ychi1x3)/Sqrt[2]),
     gc113 -> (sina*ychi1x3)/Sqrt[2],
     gc114 -> -((Sqrt[1 - sina^2]*ychi1x3)/Sqrt[2]),
     gc115 -> (sina*ychi2x3)/Sqrt[2],
     gc116 -> -((Sqrt[1 - sina^2]*ychi2x3)/Sqrt[2]),
     gc117 -> (sina*ychi2x3)/Sqrt[2],
     gc118 -> -((Sqrt[1 - sina^2]*ychi2x3)/Sqrt[2]),
     gc119R -> -ytau,
     gc121 -> -1/2*(EL*sina*(cw^2 + sw^2))/(cw*sw),
     gc122 -> -1/2*(EL*Sqrt[1 - sina^2]*(cw^2 + sw^2))/(cw*sw),
     gc123 -> -1/2*(cw*EL)/sw + (EL*sw)/(2*cw),
     gc127 -> (EL^2*vev)/(2*cw),
     gc131 -> -1/2*(EL^2*vev)/cw,
     gc132 -> (cw*EL^2)/sw,
     gc138 -> (EL^2*sina*(cw^2 + sw^2)^2*vev)/(2*cw^2*sw^2),
     gc139 -> (EL^2*Sqrt[1 - sina^2]*(cw^2 + sw^2)^2*vev)/(2*cw^2*sw^2),
     gc140 -> -((cw^2*EL^2)/sw^2),
     gc141 -> -EL,
     gc142 -> -EL,
     gc143 -> -EL,
     gc144 -> (2*EL)/3,
     gc145 -> (2*EL)/3,
     gc146 -> (2*EL)/3,
     gc147 -> -1/3*EL,
     gc148 -> -1/3*EL,
     gc149 -> -1/3*EL,
     gc150 -> GS,
     gc151 -> GS,
     gc152 -> GS,
     gc153 -> GS,
     gc154 -> GS,
     gc155 -> GS,
     gc156 -> EL/(Sqrt[2]*sw),
     gc157 -> EL/(Sqrt[2]*sw),
     gc158 -> EL/(Sqrt[2]*sw),
     gc159 -> EL/(Sqrt[2]*sw),
     gc160 -> EL/(Sqrt[2]*sw),
     gc161 -> EL/(Sqrt[2]*sw),
     gc162 -> EL/(Sqrt[2]*sw),
     gc163 -> EL/(Sqrt[2]*sw),
     gc164 -> EL/(Sqrt[2]*sw),
     gc165 -> EL/(Sqrt[2]*sw),
     gc166 -> EL/(Sqrt[2]*sw),
     gc167 -> EL/(Sqrt[2]*sw),
     gc168L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc168R -> (-2*EL*sw)/(3*cw),
     gc169L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc169R -> (-2*EL*sw)/(3*cw),
     gc170L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc170R -> (-2*EL*sw)/(3*cw),
     gc171L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc171R -> (EL*sw)/(3*cw),
     gc172L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc172R -> (EL*sw)/(3*cw),
     gc173L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc173R -> (EL*sw)/(3*cw),
     gc174 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc175 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc176 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc177L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc177R -> (EL*sw)/cw,
     gc178L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc178R -> (EL*sw)/cw,
     gc179L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc179R -> (EL*sw)/cw};

