#!/usr/bin/env python3


import numpy as np


def combineFiles(effFiles,outputFile):

    newData = None
    for effFile in effFiles:
        effData = np.genfromtxt(effFile,names=True,case_sensitive='lower',skip_header=2,delimiter=',')        
        data = list(zip(effData['ms'],effData['m1'],
                                        effData['m0'],effData['ctau'],effData['eff']))
        if newData is None:
            newData = np.array(data)
        else:
            newData = np.append(newData,data,axis=0)

    np.savetxt(outputFile,newData,delimiter=',',header='ms,m1,m0,ctau,eff',fmt='%1.3e')


if __name__ == "__main__":
    
    import argparse    
    ap = argparse.ArgumentParser(description=
            "Merge individual csv datas generated by getEffsFromROOT.py.")
    ap.add_argument('-f', '--inputFiles', required=True,nargs='+',
            help='list of csv files to be merged', default =[])
    
    ap.add_argument('-o', '--outputFile', required=False, help='output file.',
                    default='atlas_exot_2019_23_effs.csv')


    args = ap.parse_args()
    inputFiles = args.inputFiles
    outputFile = args.outputFile
    
    combineFiles(inputFiles,outputFile)







